In [5]:
import mygene
import pandas as pd

In [ ]:
# Initialize the MyGene tool
mg = mygene.MyGeneInfo()

In [ ]:
# A list of mysterious Ensembl IDs
ensembl_ids = [
    "ENSG00000139618", # We'll find out what this is!
    "ENSG00000141510",
    "ENSG00000012048",
    "ENSG00000146648"
]

In [ ]:
#Perform the translation
print("Querying the MyGene database...")

results = mg.querymany(
    ensembl_ids,
    scopes = 'ensembl.gene', # Our input format
    fields = 'symbol, name, entrezgene', # What we want back
    species = 'human'
)

print(f"Returned {len(results)} results!")

Input sequence provided is already in string format. No operation performed
Input sequence provided is already in string format. No operation performed

Querying the MyGene database...
Returned 4 results!

In [ ]:
# Convert the messy dictionary into a clean Pandas DataFrame
df = pd.DataFrame(results)

# Drop some internal APi columns we don't need ('_id' and '_score')
df = df.drop(columns=['_id', '_score'])

# Display the clean table
display(df)

             query entrezgene                              name symbol
0  ENSG00000139618        675       BRCA2 DNA repair associated  BRCA2
1  ENSG00000141510       7157                 tumor protein p53   TP53
2  ENSG00000012048        672       BRCA1 DNA repair associated  BRCA1
3  ENSG00000146648       1956  epidermal growth factor receptor   EGFR

In [ ]:
# Querying a fake ID
fake_id = ["ENSG_FAKE_12345"]
fake_result = mg.querymany(fake_id, scopes='ensembl.gene', fields = 'symbol', species = 'human')

pd.DataFrame(fake_result)

Input sequence provided is already in string format. No operation performed
Input sequence provided is already in string format. No operation performed
1 input query terms found no hit:	['ENSG_FAKE_12345']

             query  notfound
0  ENSG_FAKE_12345      True